services:

  user-service:
    image: ghcr.io/meeeiiike/user-service/app:latest
    env_file: ./.env
    depends_on:
      user-db:
        condition: service_healthy
    ports:
      - "8080:8080" #8083:8081
    networks:
      - labnet
    restart: unless-stopped

  user-db:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: appdb
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
    volumes:
      - user-postgres-data:/var/lib/postgresql/data
    networks:
      - labnet
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $DB_USER -d $DB_NAME" ]
      interval: 5s
      retries: 5

  ###########################################################

  book-service:
    image: ghcr.io/meeeiiike/book-service/app:latest
    env_file: ./.env
    ports:
      - "8081:8081"
    networks:
      - labnet

  loans-service:
    image: ghcr.io/meeeiiike/loan-service/app:latest
    env_file: ./.env
    depends_on:
      - notification-service
      - user-service
      - book-service
    ports:
      - "8082:8082"
    networks:
      - labnet

  notification-service:
    image: ghcr.io/meeeiiike/notification-service/app:latest
    env_file: ./.env
    ports:
      - "8083:8083" #8084:8081
    networks:
      - labnet

volumes:
  user-postgres-data:

networks:
  labnet: